[workspace]
members = [
  "apps/desktop",
  "apps/website",
  "crates/client",
  "crates/config",
  "crates/events",
  "crates/plugin-api",
  "crates/core",
  "crates/runtime",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
version = "0.10.1"

[workspace.lints.rust]
unsafe_code = "forbid"
